//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RebrovKorsun.Datafolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int IdDoctor { get; set; }
        public string FirstNameDoctor { get; set; }
        public string MiddleNameDoctor { get; set; }
        public string LastNameDoctor { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Phone { get; set; }
        public Nullable<int> IdJobTitle { get; set; }
        public int IdDoctorStatus { get; set; }
        public string PasstortSeria { get; set; }
        public string PassportNumber { get; set; }
        public int IdIssuedPassport { get; set; }
        public int IdWhereIssuedPassport { get; set; }
        public string PassportDepartmentCode { get; set; }
        public System.DateTime DateIssuedPassport { get; set; }
        public byte[] Photo { get; set; }
        public int IdCab { get; set; }
        public int IdDoctorCategory { get; set; }
        public int IdUser { get; set; }
    
        public virtual Cab Cab { get; set; }
        public virtual DoctorCategory DoctorCategory { get; set; }
        public virtual DoctorStatus DoctorStatus { get; set; }
        public virtual IssuedPasspot IssuedPasspot { get; set; }
        public virtual JobTitle JobTitle { get; set; }
        public virtual User User { get; set; }
        public virtual WhereIssuedPassport WhereIssuedPassport { get; set; }
    }
}
