//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RebrovKorsun.Datafolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int IdPatient { get; set; }
        public string PatientLastName { get; set; }
        public string PatientMiddleName { get; set; }
        public string PatientFirstName { get; set; }
        public int IdStatusPatient { get; set; }
        public string PhoneNumber { get; set; }
        public string PolisOMSNumber { get; set; }
        public int IdRecord { get; set; }
        public int IdUser { get; set; }
    
        public virtual Record Record { get; set; }
        public virtual User User { get; set; }
    }
}
