//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RebrovKorsun.Datafolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Record()
        {
            this.Patient = new HashSet<Patient>();
        }
    
        public int IdRecord { get; set; }
        public string RecordTime { get; set; }
        public string RecordDate { get; set; }
        public int IdDoctor { get; set; }
        public int IdCab { get; set; }
        public int IdDesease { get; set; }
        public int IdRecordStatus { get; set; }
    
        public virtual Cab Cab { get; set; }
        public virtual Disease Disease { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patient { get; set; }
        public virtual RecordStatus RecordStatus { get; set; }
    }
}
